{{- $name := printf "%s-discount-grpc" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: discount-grpc
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: discount-grpc
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: grpc
